version: ""

formatter: markdown table

name: terraform-aws-security-group-automated-cloudfront-whitelist

content: |-
  # terraform-aws-security-group-automated-cloudfront-whitelist
  
  GitHub: [StratusGrid/terraform-aws-security-group-automated-cloudfront-whitelist](https://github.com/StratusGrid/terraform-aws-security-group-automated-cloudfront-whitelist)
  
  This module provisions new security groups for allowing ingress traffic over ports 80/tcp and 443/tcp from all global and applicable regional Amazon CloudFront published IP address ranges. The security groups are updated automatically any time the published IP address ranges (https://ip-ranges.amazonaws.com/ip-ranges.json) are updated.
  
  <span style="color:red">Note:</span> Mac users need to install "md5sha1sum" package locally using the following command.
  ```bash
  brew install md5sha1sum
  ```
  ---
  ## Example
  ```hcl
  {{ include "examples/example1.tfnot" }}
  ```
  ---
  {{ .Requirements }}
  
  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements
sort:
  enabled: true
  by: name
output:
  file: README.md
  mode: replace
